version: "3"

services:

  app:
    restart: always
    build: .
    ports:
      - "4000:8080"
    networks:
        - test_net
    depends_on:
      - fluentd
    environment:
      - DEBUG
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "true"
        tag: docker

  fluentd:
    container_name: test_fluentd
    restart: always
    build: ./fluentd
    volumes:
      - $PWD/fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - test_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    networks:
      - test_net

  kibana:
    image: kibana:7.10.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - test_net

networks:
  test_net:
    driver: bridge
